trigger:
  branches:
    include:
      - issue#936 # Set your desired branch here

jobs:
  - job: Linux
    pool:
      name: "DS11"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node.js"

      - script: |

          npm install
        displayName: "Install Dependencies"

      - script: |
          npm build
        displayName: "Build"

      - script: |
          cd test
          npm test
        displayName: "Run npm test"
  - job: Windows
    pool:
      name: "DS31"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node.js"

      - script: |

          npm install
        displayName: "Install Dependencies"

      - script: |
          npm build
        displayName: "Build"

      - script: |
          cd test
          npm test
        displayName: "Run npm test"
