version: 2.1

executors:
  node-executor:
    docker:
      - image: 'node:14'  # You can change the Node.js version as needed

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build
          command: npm run build

      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
